### ISSUE TITLE
The revme host program reports error in local proving

### ISSUE THREAD

**Issue by gavin-ygy** [zkMIPS/zkm-project-template#19]
1. clone  the latest repo
  git clone  https://github.com/zkMIPS/zkm-project-template.git

2. compile the project
cd  zkm-project-template
# compile snark library
sdk/src/local/libsnark/compile.sh  
 
# build host programs
cargo build --release             

3. generate the revme's public input
cd your-work-path
git clone https://github.com/zkMIPS/revme.git
cd revme

// block 244
RPC_URL=http://localhost:8545/ CHAIN_ID=1337 BLOCK_NO=199636 RUST_LOG=debug SUITE_JSON_PATH=./test-vectors/244.json cargo run --example process

// block 199636
RPC_URL=http://localhost:8545/ CHAIN_ID=1337 BLOCK_NO=199636 RUST_LOG=debug SUITE_JSON_PATH=./test-vectors/199636.json cargo run --example process

copy test-vectors/199636.json and 244.json  to zkm-project-template project :zkm-project-template/host-program/test-vectors/ 

4. update the  zkm-project-template/host-program/run-revme-local-proving.sh  according your setting
    
5. run the script
 cd zkm-project-template/host-program
./run-revme-local-proving.sh

check the log:
tail -f   revme-local-proving.log 
```
//...  the input 244.json and 199636.json  have the same error.

[2024-10-03T03:19:20Z INFO  revme_prove] new prover client.
[2024-10-03T03:19:20Z INFO  revme_prove] new prover client,ok.
[2024-10-03T03:19:20Z INFO  zkm_sdk::local::prover] calling request_proof.
[2024-10-03T03:19:20Z INFO  zkm_sdk::local::prover] calling wait_proof, proof_id=2ae22cd2-6369-4601-820f-aee3c5104b9a
[2024-10-03T03:19:20Z INFO  zkm_sdk::local::prover] waiting the proof result.
[2024-10-03T03:19:20Z WARN  zkm_emulator::memory] write out of memory: ffff8024
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a string", line: 1, column: 876)', src/main.rs:38:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /mnt/data/.cargo/git/checkouts/zkm-2a362a43ce588637/58f7960/emulator/src/state.rs:831:17:
invalid fun when process hi lo, fun: 20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gavin-ygy** [comment]
The reason is  that the public input of the block json's format which  does not need being  with bincode::serialize_into.
