### ISSUE TITLE
sdk error

### ISSUE THREAD

**Issue by gavin-ygy** [zkMIPS/zkm-project-template#30]
1. using the latest template 
2. edit the host program 
fn set_sha2_rust_input(seg_size_u: u32, execute_only_b: bool) -> anyhow::Result<ProverInput> {
    let elf_path = env::var("ELF_PATH").expect("ELF PATH is missed");
    let num_bytes: usize = 1024; //Notice! : if this value is small, it will not generate the snark proof.
    let pri_input = vec![5u8; num_bytes];
    let mut hasher = Sha256::new();
    hasher.update(&pri_input);
    let result = hasher.finalize();
    let output: [u8; 32] = result.into();
    let public_str = hex::encode(result);    //not  bincode
    // assume the  arg[0] is the hash(input)(which is a public input), and the arg[1] is the input.
    let public_input = output.to_vec();
    let mut pub_buf = Vec::new();
    bincode::serialize_into(&mut pub_buf, &public_input)
        .expect("public_input serialization failed");
    let mut pri_buf = Vec::new();
    bincode::serialize_into(&mut pri_buf, &pri_input).expect("private_input serialization failed");
    //let public_str = String::from_utf8(pub_buf.clone())?;
    let input = ProverInput {
        elf: read(elf_path).unwrap(),
        public_inputstream: pub_buf,
        private_inputstream: pri_buf,
        seg_size: seg_size_u,
        execute_only: execute_only_b,
        args: public_str,
    };

    Ok(input)
}
3.  cargo build -r
4.   ./run-local-proving.sh sha2-rust
5.  tail -f sha2-rust-local-proving.log
[2024-10-19T06:51:50Z INFO  zkm_prove] new prover client.
[2024-10-19T06:51:50Z INFO  zkm_prove] new prover client,ok.
[2024-10-19T06:51:50Z INFO  zkm_sdk::local::prover] calling request_proof.
[2024-10-19T06:51:50Z INFO  zkm_sdk::local::prover] calling wait_proof, proof_id=e7b4e2fb-e367-4b84-ad52-c200dc5b3c2e
[2024-10-19T06:51:50Z INFO  zkm_sdk::local::prover] waiting the proof result.
[2024-10-19T06:51:50Z INFO  zkm_sdk::local::stark] args: ["1ba794e9305174cbcd58c9e8ce282af85b353d87ccd380db3a41c3bc4615d273"]
[2024-10-19T06:51:50Z INFO  zkm_emulator::utils] Split done 66951 : 89819
[2024-10-19T06:51:50Z INFO  zkm_sdk::local::stark] !!!*******seg_num:2
[2024-10-19T06:52:40Z INFO  zkm_sdk::local::util] Process segment /tmp/e7b4e2fb-e367-4b84-ad52-c200dc5b3c2e/input/segments/0
[2024-10-19T06:52:43Z INFO  zkm_prover::cpu::bootstrap_kernel] Bootstrapping took 3099 cycles
[2024-10-19T06:52:43Z INFO  zkm_prover::generation] CPU halted after 64762 cycles
[2024-10-19T06:52:43Z INFO  zkm_prover::generation] CPU trace padded to 65536 cycles
[2024-10-19T06:52:43Z INFO  zkm_prover::generation] Trace lengths (before padding): TraceCheckpoint { arithmetic_len: 18206, cpu_len: 65536, poseidon_len: 3098, poseidon_sponge_len: 3098, logic_len: 15208, memory_len: 386338 }
thread '<unnamed>' panicked at /mnt/data/.cargo/git/checkouts/zkm-2a362a43ce588637/1122bb7/prover/src/generation/mod.rs:51:5:
assertion failed: userdata.len() <= NUM_PUBLIC_INPUT_USERDATA
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at sdk/src/local/prover.rs:113:28:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by eigmax** [comment]
The first input, which is a public input, should be of size 32-byte
